# Generated by Django 4.2.4 on 2023-10-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_user_phone_number_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
